INSERT INTO publishers(name) VALUES ('Юрайт');
INSERT INTO publishers(name) VALUES ('НИЦ-ИНФРА-М');
INSERT INTO publishers(name) VALUES ('Издательский Центр "Академя"');
INSERT INTO publishers(name) VALUES ('КноРУС');
INSERT INTO publishers(name) VALUES ('Питер');

INSERT INTO publications(name, issues_per_year) VALUES ('Научные открытия',10);
INSERT INTO publications(name, issues_per_year) VALUES ('Исследования и технологии',42);
INSERT INTO publications(name, issues_per_year) VALUES ('Биологический мир',25);
INSERT INTO publications(name, issues_per_year) VALUES ('Физика сегодня',31);
INSERT INTO publications(name, issues_per_year) VALUES ('Химические исследования',5);
INSERT INTO publications(name, issues_per_year) VALUES ('Медицинские новости',13);
INSERT INTO publications(name, issues_per_year) VALUES ('Технический прогресс',20);
INSERT INTO publications(name, issues_per_year) VALUES ('Экология и природа',39);
INSERT INTO publications(name, issues_per_year) VALUES ('Социальные науки',17);
INSERT INTO publications(name, issues_per_year) VALUES ('Инновации и разработки',32);

INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (1,1);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (1,2);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (1,3);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (2,4);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (3,5);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (3,6);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (3,7);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (4,8);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (5,9);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (5,1);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (1,4);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (2,5);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (4,3);
INSERT INTO publishers_publications(publisher_id, publication_id) VALUES (4,1);

INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (1,10,'2010-01-22');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (2,12,'2022-05-23');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (3,32,'2021-10-23');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (4,19,'2020-10-22');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (5,9,'2002-06-20');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (6,1,'2016-04-20');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (7,3,'2017-07-13');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (8,23,'2011-11-19');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (9,12,'2009-01-01');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (10,31,'2021-08-31');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (10,13,'2021-08-31');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (10,9,'2021-08-31');
INSERT INTO publication_issues(publication_id, issue_number, publication_date) VALUES (3,16,'2021-08-31');

INSERT INTO articles(author, name) VALUES ('Иванов Петр Алексеевич', 'Методы исследования природы');
INSERT INTO articles(author, name) VALUES ('Смирнова Елена Владимировна', 'Анализ образовательных систем');
INSERT INTO articles(author, name) VALUES ('Козлов Андрей Михайлович', 'Развитие искусственного интеллекта');
INSERT INTO articles(author, name) VALUES ('Петров Дмитрий Сергеевич', 'Исследование космических объектов');
INSERT INTO articles(author, name) VALUES ('Соколова Анастасия Ивановна', 'Биологические открытия');
INSERT INTO articles(author, name) VALUES ('Григорьев Виктор Павлович', 'Физика элементарных частиц');
INSERT INTO articles(author, name) VALUES ('Лебедева Ольга Анатольевна', 'Новые технологии в медицине');
INSERT INTO articles(author, name) VALUES ('Ковалев Игорь Николаевич', 'Экологические исследования');
INSERT INTO articles(author, name) VALUES ('Смирнова Елена Владимировна', 'Социальная психология');
INSERT INTO articles(author, name) VALUES ('Зайцева Мария Александровна', 'История искусства');
INSERT INTO articles(author, name) VALUES ('Смирнова Елена Владимировна', 'Новые методы лечения рака');
INSERT INTO articles(author, name) VALUES ('Алексеева Татьяна Игоревна', 'Исследование изменений климата');
INSERT INTO articles(author, name) VALUES ('Зайцева Мария Александровна', 'Технический прогресс');
INSERT INTO articles(author, name) VALUES ('Васильева Екатерина Дмитриевна', 'Искусственный интеллект в образовании');
INSERT INTO articles(author, name) VALUES ('Павлов Денис Сергеевич', 'Роль генетики в заболеваниях');

INSERT INTO articles_publications(article_id, publication_id) VALUES (1,1);
INSERT INTO articles_publications(article_id, publication_id) VALUES (2,2);
INSERT INTO articles_publications(article_id, publication_id) VALUES (3,3);
INSERT INTO articles_publications(article_id, publication_id) VALUES (4,4);
INSERT INTO articles_publications(article_id, publication_id) VALUES (5,5);
INSERT INTO articles_publications(article_id, publication_id) VALUES (6,6);
INSERT INTO articles_publications(article_id, publication_id) VALUES (7,7);
INSERT INTO articles_publications(article_id, publication_id) VALUES (8,8);
INSERT INTO articles_publications(article_id, publication_id) VALUES (9,9);
INSERT INTO articles_publications(article_id, publication_id) VALUES (10,10);
INSERT INTO articles_publications(article_id, publication_id) VALUES (11,10);
INSERT INTO articles_publications(article_id, publication_id) VALUES (12,10);
INSERT INTO articles_publications(article_id, publication_id) VALUES (13,1);
INSERT INTO articles_publications(article_id, publication_id) VALUES (14,2);
INSERT INTO articles_publications(article_id, publication_id) VALUES (15,3);