INSERT INTO publishers(name) VALUES ('Юрайт');
INSERT INTO publishers(name) VALUES ('НИЦ-ИНФРА-М');
INSERT INTO publishers(name) VALUES ('Издательский Центр "Академя"');
INSERT INTO publishers(name) VALUES ('КноРУС');
INSERT INTO publishers(name) VALUES ('Питер');

INSERT INTO publications(name, issues_per_year) VALUES ('Научные открытия',10);
INSERT INTO publications(name, issues_per_year) VALUES ('Исследования и технологии',42);
INSERT INTO publications(name, issues_per_year) VALUES ('Биологический мир',25);
INSERT INTO publications(name, issues_per_year) VALUES ('Физика сегодня',31);
INSERT INTO publications(name, issues_per_year) VALUES ('Химические исследования',5);
INSERT INTO publications(name, issues_per_year) VALUES ('Медицинские новости',13);
INSERT INTO publications(name, issues_per_year) VALUES ('Технический прогресс',20);
INSERT INTO publications(name, issues_per_year) VALUES ('Экология и природа',39);
INSERT INTO publications(name, issues_per_year) VALUES ('Социальные науки',17);
INSERT INTO publications(name, issues_per_year) VALUES ('Инновации и разработки',32);

SELECT insert_publisher_publication(publisher_id := 1, publication_id := 1, publication_date := '2013-12-21');
SELECT insert_publisher_publication(publisher_id := 1, publication_id := 2, publication_date := '2010-01-22');
SELECT insert_publisher_publication(publisher_id := 1, publication_id := 3, publication_date := '2022-05-23');
SELECT insert_publisher_publication(publisher_id := 2, publication_id := 4, publication_date := '2021-10-23');
SELECT insert_publisher_publication(publisher_id := 3, publication_id := 5, publication_date := '2020-10-22');
SELECT insert_publisher_publication(publisher_id := 3, publication_id := 6, publication_date := '2002-06-20');
SELECT insert_publisher_publication(publisher_id := 3, publication_id := 7, publication_date := '2016-04-20');
SELECT insert_publisher_publication(publisher_id := 4, publication_id := 8, publication_date := '2017-07-13');
SELECT insert_publisher_publication(publisher_id := 5, publication_id := 9, publication_date := '2011-11-19');
SELECT insert_publisher_publication(publisher_id := 5, publication_id := 10, publication_date := '2009-01-01');
SELECT insert_publisher_publication(publisher_id := 1, publication_id := 4, publication_date := '2021-08-31');
SELECT insert_publisher_publication(publisher_id := 2, publication_id := 5, publication_date := '2021-08-31');
SELECT insert_publisher_publication(publisher_id := 4, publication_id := 3, publication_date := '2021-08-31');
SELECT insert_publisher_publication(publisher_id := 4, publication_id := 10, publication_date := '2021-08-31');

INSERT INTO articles(author, name) VALUES ('Иванов Петр Алексеевич', 'Методы исследования природы');
INSERT INTO articles(author, name) VALUES ('Смирнова Елена Владимировна', 'Анализ образовательных систем');
INSERT INTO articles(author, name) VALUES ('Козлов Андрей Михайлович', 'Развитие искусственного интеллекта');
INSERT INTO articles(author, name) VALUES ('Петров Дмитрий Сергеевич', 'Исследование космических объектов');
INSERT INTO articles(author, name) VALUES ('Соколова Анастасия Ивановна', 'Биологические открытия');
INSERT INTO articles(author, name) VALUES ('Григорьев Виктор Павлович', 'Физика элементарных частиц');
INSERT INTO articles(author, name) VALUES ('Лебедева Ольга Анатольевна', 'Новые технологии в медицине');
INSERT INTO articles(author, name) VALUES ('Ковалев Игорь Николаевич', 'Экологические исследования');
INSERT INTO articles(author, name) VALUES ('Смирнова Елена Владимировна', 'Социальная психология');
INSERT INTO articles(author, name) VALUES ('Зайцева Мария Александровна', 'История искусства');
INSERT INTO articles(author, name) VALUES ('Смирнова Елена Владимировна', 'Новые методы лечения рака');
INSERT INTO articles(author, name) VALUES ('Алексеева Татьяна Игоревна', 'Исследование изменений климата');
INSERT INTO articles(author, name) VALUES ('Зайцева Мария Александровна', 'Технический прогресс');
INSERT INTO articles(author, name) VALUES ('Васильева Екатерина Дмитриевна', 'Искусственный интеллект в образовании');
INSERT INTO articles(author, name) VALUES ('Павлов Денис Сергеевич', 'Роль генетики в заболеваниях');

INSERT INTO article_publications(article_id, publication_id) VALUES (1,1);
INSERT INTO article_publications(article_id, publication_id) VALUES (2,2);
INSERT INTO article_publications(article_id, publication_id) VALUES (3,3);
INSERT INTO article_publications(article_id, publication_id) VALUES (4,4);
INSERT INTO article_publications(article_id, publication_id) VALUES (5,5);
INSERT INTO article_publications(article_id, publication_id) VALUES (6,6);
INSERT INTO article_publications(article_id, publication_id) VALUES (7,7);
INSERT INTO article_publications(article_id, publication_id) VALUES (8,8);
INSERT INTO article_publications(article_id, publication_id) VALUES (9,9);
INSERT INTO article_publications(article_id, publication_id) VALUES (10,10);
INSERT INTO article_publications(article_id, publication_id) VALUES (11,10);
INSERT INTO article_publications(article_id, publication_id) VALUES (12,10);
INSERT INTO article_publications(article_id, publication_id) VALUES (13,1);
INSERT INTO article_publications(article_id, publication_id) VALUES (14,2);
INSERT INTO article_publications(article_id, publication_id) VALUES (15,3);