CREATE TABLE Publishers
(
    id   bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) UNIQUE NOT NULL
);

CREATE TABLE Publications
(
    id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            varchar(100) NOT NULL,
    issues_per_year int CHECK ( issues_per_year >= 0 )
);

CREATE TABLE Publishers_Publications
(
    publisher_id     bigint REFERENCES Publishers (id),
    publication_id   bigint REFERENCES Publications (id),
    issue            int NOT NULL,
    publication_date date,
    PRIMARY KEY (publisher_id, publication_id)
);

CREATE TABLE Articles
(
    id     bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author varchar(100) NOT NULL,
    name   varchar(150) NOT NULL,
    UNIQUE (author, name)
);

CREATE TABLE Article_Publications
(
    article_id     bigint REFERENCES Articles (id),
    publication_id bigint REFERENCES Publications (id),
    PRIMARY KEY (article_id, publication_id)
);